services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MoviesDB-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "14330:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
