// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250410130613_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Runtime")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 1. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular1.jpg",
                            Rating = 1,
                            ReleaseDate = new DateTime(2016, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 121,
                            Title = "Popular Movie Title 1"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 2. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular2.jpg",
                            Rating = 2,
                            ReleaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 122,
                            Title = "Popular Movie Title 2"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 3. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular3.jpg",
                            Rating = 3,
                            ReleaseDate = new DateTime(2018, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 123,
                            Title = "Popular Movie Title 3"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 4. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular4.jpg",
                            Rating = 4,
                            ReleaseDate = new DateTime(2019, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 124,
                            Title = "Popular Movie Title 4"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 5. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular5.jpg",
                            Rating = 5,
                            ReleaseDate = new DateTime(2020, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 125,
                            Title = "Popular Movie Title 5"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 6. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular6.jpg",
                            Rating = 6,
                            ReleaseDate = new DateTime(2021, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 126,
                            Title = "Popular Movie Title 6"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 7. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular7.jpg",
                            Rating = 7,
                            ReleaseDate = new DateTime(2022, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 127,
                            Title = "Popular Movie Title 7"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 8. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular8.jpg",
                            Rating = 8,
                            ReleaseDate = new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 128,
                            Title = "Popular Movie Title 8"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 9. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular9.jpg",
                            Rating = 9,
                            ReleaseDate = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 129,
                            Title = "Popular Movie Title 9"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 10. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular10.jpg",
                            Rating = 10,
                            ReleaseDate = new DateTime(2015, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 130,
                            Title = "Popular Movie Title 10"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 11. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular11.jpg",
                            Rating = 0,
                            ReleaseDate = new DateTime(2016, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 131,
                            Title = "Popular Movie Title 11"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 12. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular12.jpg",
                            Rating = 1,
                            ReleaseDate = new DateTime(2017, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 132,
                            Title = "Popular Movie Title 12"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 13. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular13.jpg",
                            Rating = 2,
                            ReleaseDate = new DateTime(2018, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 133,
                            Title = "Popular Movie Title 13"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 14. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular14.jpg",
                            Rating = 3,
                            ReleaseDate = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 134,
                            Title = "Popular Movie Title 14"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 15. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular15.jpg",
                            Rating = 4,
                            ReleaseDate = new DateTime(2020, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 135,
                            Title = "Popular Movie Title 15"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 16. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular16.jpg",
                            Rating = 5,
                            ReleaseDate = new DateTime(2021, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 136,
                            Title = "Popular Movie Title 16"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 17. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular17.jpg",
                            Rating = 6,
                            ReleaseDate = new DateTime(2022, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 137,
                            Title = "Popular Movie Title 17"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 18. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular18.jpg",
                            Rating = 7,
                            ReleaseDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 138,
                            Title = "Popular Movie Title 18"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 19. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular19.jpg",
                            Rating = 8,
                            ReleaseDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 139,
                            Title = "Popular Movie Title 19"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 20. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular20.jpg",
                            Rating = 9,
                            ReleaseDate = new DateTime(2015, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 140,
                            Title = "Popular Movie Title 20"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 21. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular21.jpg",
                            Rating = 10,
                            ReleaseDate = new DateTime(2016, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 141,
                            Title = "Popular Movie Title 21"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 22. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular22.jpg",
                            Rating = 0,
                            ReleaseDate = new DateTime(2017, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 142,
                            Title = "Popular Movie Title 22"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 23. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular23.jpg",
                            Rating = 1,
                            ReleaseDate = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 143,
                            Title = "Popular Movie Title 23"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 24. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular24.jpg",
                            Rating = 2,
                            ReleaseDate = new DateTime(2019, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 144,
                            Title = "Popular Movie Title 24"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 25. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular25.jpg",
                            Rating = 3,
                            ReleaseDate = new DateTime(2020, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 145,
                            Title = "Popular Movie Title 25"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 26. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular26.jpg",
                            Rating = 4,
                            ReleaseDate = new DateTime(2021, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 146,
                            Title = "Popular Movie Title 26"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 27. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular27.jpg",
                            Rating = 5,
                            ReleaseDate = new DateTime(2022, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 147,
                            Title = "Popular Movie Title 27"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 28. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular28.jpg",
                            Rating = 6,
                            ReleaseDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 148,
                            Title = "Popular Movie Title 28"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 29. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular29.jpg",
                            Rating = 7,
                            ReleaseDate = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 149,
                            Title = "Popular Movie Title 29"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 30. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular30.jpg",
                            Rating = 8,
                            ReleaseDate = new DateTime(2015, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 120,
                            Title = "Popular Movie Title 30"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 31. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular31.jpg",
                            Rating = 9,
                            ReleaseDate = new DateTime(2016, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 121,
                            Title = "Popular Movie Title 31"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 32. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular32.jpg",
                            Rating = 10,
                            ReleaseDate = new DateTime(2017, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 122,
                            Title = "Popular Movie Title 32"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 33. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular33.jpg",
                            Rating = 0,
                            ReleaseDate = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 123,
                            Title = "Popular Movie Title 33"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 34. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular34.jpg",
                            Rating = 1,
                            ReleaseDate = new DateTime(2019, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 124,
                            Title = "Popular Movie Title 34"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 35. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular35.jpg",
                            Rating = 2,
                            ReleaseDate = new DateTime(2020, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 125,
                            Title = "Popular Movie Title 35"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 36. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular36.jpg",
                            Rating = 3,
                            ReleaseDate = new DateTime(2021, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 126,
                            Title = "Popular Movie Title 36"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 37. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular37.jpg",
                            Rating = 4,
                            ReleaseDate = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 127,
                            Title = "Popular Movie Title 37"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 38. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular38.jpg",
                            Rating = 5,
                            ReleaseDate = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 128,
                            Title = "Popular Movie Title 38"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 39. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular39.jpg",
                            Rating = 6,
                            ReleaseDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 129,
                            Title = "Popular Movie Title 39"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 40. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular40.jpg",
                            Rating = 7,
                            ReleaseDate = new DateTime(2015, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 130,
                            Title = "Popular Movie Title 40"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 41. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular41.jpg",
                            Rating = 8,
                            ReleaseDate = new DateTime(2016, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 131,
                            Title = "Popular Movie Title 41"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 42. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular42.jpg",
                            Rating = 9,
                            ReleaseDate = new DateTime(2017, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 132,
                            Title = "Popular Movie Title 42"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 43. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular43.jpg",
                            Rating = 10,
                            ReleaseDate = new DateTime(2018, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 133,
                            Title = "Popular Movie Title 43"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 44. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular44.jpg",
                            Rating = 0,
                            ReleaseDate = new DateTime(2019, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 134,
                            Title = "Popular Movie Title 44"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 45. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular45.jpg",
                            Rating = 1,
                            ReleaseDate = new DateTime(2020, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 135,
                            Title = "Popular Movie Title 45"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 46. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular46.jpg",
                            Rating = 2,
                            ReleaseDate = new DateTime(2021, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 136,
                            Title = "Popular Movie Title 46"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 47. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular47.jpg",
                            Rating = 3,
                            ReleaseDate = new DateTime(2022, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 137,
                            Title = "Popular Movie Title 47"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 48. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular48.jpg",
                            Rating = 4,
                            ReleaseDate = new DateTime(2023, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 138,
                            Title = "Popular Movie Title 48"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 49. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular49.jpg",
                            Rating = 5,
                            ReleaseDate = new DateTime(2024, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 139,
                            Title = "Popular Movie Title 49"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 50. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular50.jpg",
                            Rating = 6,
                            ReleaseDate = new DateTime(2015, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 140,
                            Title = "Popular Movie Title 50"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 51. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular51.jpg",
                            Rating = 7,
                            ReleaseDate = new DateTime(2016, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 141,
                            Title = "Popular Movie Title 51"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 52. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular52.jpg",
                            Rating = 8,
                            ReleaseDate = new DateTime(2017, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 142,
                            Title = "Popular Movie Title 52"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000053"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 53. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular53.jpg",
                            Rating = 9,
                            ReleaseDate = new DateTime(2018, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 143,
                            Title = "Popular Movie Title 53"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000054"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 54. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular54.jpg",
                            Rating = 10,
                            ReleaseDate = new DateTime(2019, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 144,
                            Title = "Popular Movie Title 54"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000055"),
                            Genres = "Comedy,Romance",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 55. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular55.jpg",
                            Rating = 0,
                            ReleaseDate = new DateTime(2020, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 145,
                            Title = "Popular Movie Title 55"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000056"),
                            Genres = "Drama,Thriller",
                            Language = "English",
                            Overview = "Overview for popular movie 56. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular56.jpg",
                            Rating = 1,
                            ReleaseDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 146,
                            Title = "Popular Movie Title 56"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000057"),
                            Genres = "Action,Adventure",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 57. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular57.jpg",
                            Rating = 2,
                            ReleaseDate = new DateTime(2022, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 147,
                            Title = "Popular Movie Title 57"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000058"),
                            Genres = "Comedy,Romance",
                            Language = "English",
                            Overview = "Overview for popular movie 58. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular58.jpg",
                            Rating = 3,
                            ReleaseDate = new DateTime(2023, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 148,
                            Title = "Popular Movie Title 58"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000059"),
                            Genres = "Drama,Thriller",
                            Language = "Spanish",
                            Overview = "Overview for popular movie 59. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular59.jpg",
                            Rating = 4,
                            ReleaseDate = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 149,
                            Title = "Popular Movie Title 59"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000060"),
                            Genres = "Action,Adventure",
                            Language = "English",
                            Overview = "Overview for popular movie 60. It's quite an interesting film about many things.",
                            PosterUrl = "/posters/popular60.jpg",
                            Rating = 5,
                            ReleaseDate = new DateTime(2015, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 120,
                            Title = "Popular Movie Title 60"
                        },
                        new
                        {
                            Id = new Guid("0d297f3c-b3fd-4425-9f34-a028c463e27c"),
                            Genres = "Adventure,Action,Thriller",
                            Language = "English",
                            Overview = "A police officer is brought out of suspended animation in prison to pursue.",
                            PosterUrl = "/posters/DemolitionMan.jpg",
                            Rating = 6,
                            ReleaseDate = new DateTime(1993, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 115,
                            Title = "Demolition Man"
                        },
                        new
                        {
                            Id = new Guid("21564b30-2e22-4b32-b139-d831218ae401"),
                            Genres = "Adventure,Action,Thriller",
                            Language = "English",
                            Overview = " deadly threat from Earth's history reappears and a hunt for a lost artifact takes place.",
                            PosterUrl = "/posters/TransformersTheLastKnight.jpg",
                            Rating = 5,
                            ReleaseDate = new DateTime(2017, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 155,
                            Title = "Transformers: The Last Knight"
                        },
                        new
                        {
                            Id = new Guid("de9f6727-6d75-49ae-a6df-7e4d827dfc25"),
                            Genres = "Adventure,Action,Comedy",
                            Language = "English",
                            Overview = "When Guy, a bank teller, learns that he is a non-player character in a bloodthirsty,.",
                            PosterUrl = "/posters/FreeGuy.jpg",
                            Rating = 7,
                            ReleaseDate = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Runtime = 115,
                            Title = "Free Guy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
